name: CI CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
    
jobs:
  pm2-restart-workflow:
    runs-on: self-hosted
    steps:

      - name: clone changes
        working-directory: /home/ubuntu/var/www/HelloWorldAws
        run: git pull
        
      - name: pm2 restart
        run: pm2 restart 0
